services:
  prometheus:
    image: prom/prometheus:v2.8.1
    volumes:
      - ./prometheus/entrypoint.sh:/bin/prometheus-entrypoint.sh
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    user: root
    entrypoint:
      - /bin/sh
      - /bin/prometheus-entrypoint.sh
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    network_mode: "host"

  grafana:
    image: grafana/grafana:9.5.19
    volumes: 
      - ../grafana/plugins/cinnamon-prometheus-app:/var/lib/grafana/plugins/cinnamon-prometheus-app
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    network_mode: "host"
    depends_on: ["prometheus"]
