# Compatible with both x86 and ARM architectures
FROM eclipse-temurin:21.0.3_9-jre-alpine

WORKDIR /usr/app

# Bin script requires bash to work
RUN apk add --no-cache bash

COPY --from=mrmarcosrolando/fiubakka-server:build-latest /usr/app/target/universal/stage /usr/app/stage

EXPOSE 2020/tcp

CMD ["bash", "-c", "JAVA_OPTS='--add-opens=java.base/sun.nio.ch=ALL-UNNAMED' ./stage/bin/fiubakka-server -J-Xmx2048m"]
