version: '3.8'

services:
  postgres:
    image: postgres:15.5 # Matches the embedded Postgres version in the Dev Image
    container_name: akka-backend-tp-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: akka
      POSTGRES_USER: akka
      POSTGRES_PASSWORD: akka
    volumes:
      - .docker/durable_state.sql:/docker-entrypoint-initdb.d/durable_state.sql
      - postgres_data:/var/lib/postgresql/data

  # See https://hub.docker.com/r/bitnami/kafka
  # for configuration reference
  kafka:
    image: bitnami/kafka:3.6.0
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      #
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - "kafka_data:/bitnami"

volumes:
  kafka_data:
    driver: local
  postgres_data:
