# Not using Alpine version for building because it breaks protoc plugin compilation
FROM sbtscala/scala-sbt:eclipse-temurin-jammy-22_36_1.10.0_3.4.2

WORKDIR /usr/app

COPY ./lightbend.sbt .
COPY ./build.sbt .
COPY ./project project/

# Install dependencies
RUN sbt update

COPY ./src src/

# Generate JAR bundle
RUN sbt clean assembly
