version: '3.8'

services:
  postgres:
    image: postgres:16.1
    container_name: akka-backend-tp-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: akka
      POSTGRES_USER: akka
      POSTGRES_PASSWORD: akka
    volumes:
      - .docker/durable_state.sql:/docker-entrypoint-initdb.d/durable_state.sql
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka 
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1 
      KAFKA_CREATE_TOPICS: "test:1:1,test2:1:1,test3:1:1,test4:1:1,test5:1:1,test6:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
