version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - dockerhub-deploy:
          filters:
            branches:
              only:
                - test-circleci

jobs:
  dockerhub-deploy:
    docker:
      - image: cimg/python:3.12.2
    environment:
      CIRCLE_PIPELINE_NUMBER: << pipeline.number >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set up SSH keys
          command: |
            mkdir -p ~/.ssh/
            echo "${SSH_PRIVATE_KEY_PROTOBUF_REPO}" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Install Dagger CLI
          command: curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
      - run:
          name: Install Dagger Python SDK
          command: pip install -r requirements.txt
      - run:
          name: Release and deploy with Dagger
          command: dagger run python .dagger/build.py
