version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - prod-dockerhub-deploy:
          filters:
            tags:
              only:
                - /^v\d{4}\.\d{2}\.\d{2}$/
            branches:
              ignore: /.*/

jobs:
  prod-dockerhub-deploy:
    docker:
      - image: cimg/python:3.12.2
    resource_class: arm.medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dagger CLI
          command: curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
      - run:
          name: Install Dagger Python SDK
          command: pip install -r requirements.txt
      - add_ssh_keys:
          fingerprints:
            - "SHA256:InMJEfM+WEGeRHaFZk2Xym9rPfkz9baIRODMhw1nJ6I"
      - run:
          name: Release and deploy with Dagger
          command: $HOME/.local/bin/dagger --progress plain run python .dagger/build.py
          environment:
            ENV: prod
