image:
  tag: 9.5.19 # Latest compatible version with the Cinnamon plugin

service:
  type: LoadBalancer
  port: 3000

grafana.ini:
  plugins:
    allow_loading_unsigned_plugins: "cinnamon-prometheus-app" # Required for unsigned plugins such as Cinnamon

persistence:
  enabled: true

extraVolumeMounts:
  - name: grafana-plugins
    mountPath: /var/lib/grafana/plugins

extraVolumes:
  - name: grafana-plugins
    existingClaim: grafana-plugins-pvc
