listeners:
  client:
    protocol: PLAINTEXT

controller:
  resources:
    limits:
      memory: 2048Mi

provisioning:
  enabled: true

  topics:
    - name: game-zone
      partitions: 4

extraConfig: |
  log.retention.minutes=2
  log.retention.check.interval.ms=30000
