apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: game-system
  name: game-system
  namespace: game-system-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-system
  template:
    metadata:
      labels:
        app: game-system
    spec:
      containers:
      - name: game-system
        image: akka-backend-tp:1.0
        readinessProbe:
          httpGet:
            path: "/ready"
            port: management
          periodSeconds: 10
          failureThreshold: 10
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: "/alive"
            port: management
          periodSeconds: 10
          failureThreshold: 10
          initialDelaySeconds: 20
        ports:
        - name: management
          containerPort: 8558
          protocol: TCP
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          # We don't set cpu limit because is not recommended in JVM
          # See https://doc.akka.io/docs/akka-management/current/kubernetes-deployment/preparing-for-production.html
          limits:
            memory: 1024Mi
          requests:
            cpu: 2
            memory: 1024Mi

---
apiVersion: v1
kind: Service
metadata:
  name: game-system-service
  namespace: game-system-1
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: game-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: game-system-1
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: game-system-1
subjects:
- kind: User
  name: system:serviceaccount:game-system-1:default
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-patcher
  namespace: game-system-1
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: annotate-pods
  namespace: game-system-1
subjects:
  - kind: User
    name: system:serviceaccount:game-system-1:default
roleRef:
  kind: Role
  name: pod-patcher
  apiGroup: rbac.authorization.k8s.io
