apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  akka.sql: |-
    {{ .Files.Get ".docker/akka.sql" | indent 4 }}
  durable_state.sql: |-
    {{ .Files.Get ".docker/durable_state.sql" | indent 4 }}

---

apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init-job
spec:
  template:
    spec:
      containers:
      - name: postgres-client
        image: bitnami/postgresql:15.5.0
        command: ["/bin/bash", "-c"]
        args: ["psql -h fiubakka-postgres-postgresql.game-system-1.svc.cluster.local -f /var/lib/postgresql/data/akka.sql && PGPASSWORD=akka psql -h fiubakka-postgres-postgresql.game-system-1.svc.cluster.local -U akka -d akka -f /var/lib/postgresql/data/durable_state.sql"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: init-scripts
          mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: init-scripts
        configMap:
          name: postgres-init-scripts
  backoffLimit: 4
