apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-plugins-pvc
  namespace: fiubakka-server-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: grafana-plugins-tmp
spec:
  restartPolicy: Never
  containers:
  - name: grafana-plugins-tmp
    image: busybox
    command: ['sh', '-c', 'sleep 120']
    volumeMounts:
    - mountPath: /var/lib/grafana/plugins
      name: grafana-plugins
  volumes:
  - name: grafana-plugins
    persistentVolumeClaim:
      claimName: grafana-plugins-pvc
