CREATE DATABASE akka;

CREATE USER akka WITH PASSWORD 'akka';
GRANT ALL PRIVILEGES ON DATABASE akka TO akka;

\c akka;

GRANT USAGE, CREATE ON SCHEMA akka TO akka;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA akka TO akka;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA akka TO akka;
