#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

check_common_files() {
  git diff --name-only --cached > /tmp/cached_files
  git diff --name-only > /tmp/all_files

  sort /tmp/cached_files -o /tmp/cached_files
  sort /tmp/all_files -o /tmp/all_files

  common_files=$(comm -12 /tmp/cached_files /tmp/all_files)

  if [ -n "$common_files" ]; then
    return 0
  fi

  return 1
}

if git diff --name-only --cached | grep -q '^src/'; then
  echo "Running scalafix and scalafmt."
  sbt ";scalafix;scalafmt"
else
  exit 0
fi

if check_common_files; then
  echo "A staged file was modified. Please add the changes and commit again"
  exit 1
else
  echo "No formatting or linting issues found."
  exit 0
fi
