name: 'dev-dockerhub-deploy'

on:
  push:
    branches:
      - main

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'
      - 
        name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY_PROTOBUF_REPO }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      -
        name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.10.3 sh; cd -; }
      -
        name: Install Dagger Python SDK
        run: pip install -r requirements.txt
      -
        name: Release and deploy with Dagger
        run: dagger run python .dagger/build.py
        env:
          ENV: dev
          DOCKER_USER: ${{ vars.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_REPO: ${{ vars.DOCKER_REPO }}
